# Generated by Django 4.1.5 on 2023-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('counter', models.CharField(max_length=200, verbose_name='Название')),
                ('whos', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
    ]
