# Generated by Django 4.1.5 on 2023-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='current_count',
            field=models.FloatField(verbose_name='Нынешнее значение счетчика'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='last_count',
            field=models.FloatField(verbose_name='Последнее оплаченное значение счетчика'),
        ),
        migrations.AlterField(
            model_name='bill_rate',
            name='cost',
            field=models.FloatField(verbose_name='Тариф'),
        ),
    ]
