# Generated by Django 4.1.5 on 2023-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес'),
        ),
    ]
