# Generated by Django 4.1.5 on 2023-02-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='allows',
            field=models.CharField(default='1', max_length=1, verbose_name='Разрешение'),
        ),
    ]
