# Generated by Django 4.1.5 on 2023-02-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='vision',
            field=models.CharField(default=1, max_length=2, verbose_name='Видна ли она админу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='counter',
            field=models.CharField(max_length=200, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='whos',
            field=models.CharField(max_length=200, verbose_name='Чей'),
        ),
    ]
