# Generated by Django 4.1.5 on 2023-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_name',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
