# Generated by Django 4.1.5 on 2023-02-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
    ]
