# Generated by Django 4.1.5 on 2023-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bill_time_pay_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time_pay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
