# Generated by Django 4.1.5 on 2023-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bill_current_count_alter_bill_last_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='report',
            name='time_update',
        ),
        migrations.AddField(
            model_name='bill_name',
            name='default_rate',
            field=models.CharField(default=1, max_length=100, verbose_name='Стандартное значение при создании счетичка'),
            preserve_default=False,
        ),
    ]
