# Generated by Django 4.1.5 on 2023-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_new_time_update_remove_report_time_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_name',
            name='default_rate',
            field=models.SmallIntegerField(verbose_name='Стандартное значение при создании счетичка'),
        ),
    ]
