# Generated by Django 4.1.5 on 2023-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
