# Generated by Django 4.1.5 on 2023-02-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dist',
            new_name='district',
        ),
    ]
