# Generated by Django 4.1.5 on 2023-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_new_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
