# Generated by Django 4.1.5 on 2023-02-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bill_name_default_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Для оплаты'),
            preserve_default=False,
        ),
    ]
