# Generated by Django 4.1.5 on 2023-02-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bill_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_rate',
            name='district',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
    ]
