# Generated by Django 4.1.5 on 2023-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_want_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='a_text',
            field=models.TextField(blank=True, verbose_name='Содержание ответа'),
        ),
        migrations.AddField(
            model_name='report',
            name='a_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название ответа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='want_staff',
            field=models.BooleanField(verbose_name='Хочет быть админом'),
        ),
    ]
