# Generated by Django 4.1.5 on 2023-03-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bill_rate_bill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(default='dsfdsfs', max_length=255, verbose_name='Название счета'),
            preserve_default=False,
        ),
    ]
