# Generated by Django 4.1.5 on 2023-03-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bill_bill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_name',
        ),
    ]
