# Generated by Django 4.1.5 on 2023-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_changedistict'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=100, unique=True, verbose_name='Район'),
        ),
    ]
